version: '3.9'
networks:
    dev:
        driver: 'bridge'
services:
    redis:
        image: 'bitnami/redis:latest'
        environment:
            - 'REDIS_REPLICATION_MODE=master'
            - 'REDIS_PORT_NUMBER=6380'
            - 'REDIS_PASSWORD=redispassword'
        networks:
            - 'dev'
        ports:
            - '6380:6380'
